highlight link cssTagName Identifier
highlight link cssUnitDecorators Normal
highlight link cssAtRule Identifier
highlight link cssAtKeyword Identifier
highlight link cssBraces Normal
highlight link cssBackgroundAttr Function
highlight link cssPseudoClassId Normal
highlight link cssAttributeSelector Normal
highlight link cssImportant Constant
highlight link cssProp Normal
highlight link cssMediaProp Normal
