highlight link svelteKey Identifier
highlight link svelteBlockStart Identifier
highlight link svelteAtTags Identifier
highlight link javascriptSvelteScript Identifier
highlight link htmlSvelteTemplate Normal
